Develop
Stupidman00/crep pull request #1
Opened 2017-03-23 16:14 UTC by Stupidman00

Я уверен, что многое нужно доработать, но я не знаю, что конкретно.

1. Для автоматического тестирования будет необходимо вручную создать входной файл и вручную прописать тестовые сценарии. Можно ли как-либо упростить этот процесс? Что полезно почитать на данную тему?

2. Ядро приложения представляет результаты работы в виде простого текстового файла. При этом этот файл является побочным эффектом работы фильтра и выходное представление наверное должно знать об этом файле и заботиться об его удалении после выполнения программы. Можно ли организовать вывод более гибким и элегантным способом, имея возможность легко изменять выходное представление?

3. При создании запроса я явно описываю все 8 вариантов значении опции и вызываю соответствующий предикат. Можно ли описать их не так явно или рассматривать опции более независимо друг от друга?

2017-03-27 13:23 UTC, gagarski requested changes

2017-03-27 13:23 UTC, gagarski commented on src/Filter.kt
> +    fun filter() {
Универсальнее было бы передать входной поток и выходной поток в функцию `filter()`. Создание промежуточных (или не промежуточных) файлов тогда будет в клиентском коде.

2017-03-27 13:23 UTC, gagarski commented on src/Request.kt
> +    class RequestBuilder(private val word: String) {
Нужен ли здесь билдер? Можно вместо него сделать конструктор с аргументами по умолчанию и вызывать его передавая именованные аргументы.

2017-03-27 13:23 UTC, gagarski commented on src/Request.kt
> +            regex = !regex
(В отрыве от комментария выше)
`regex = !regex` - это очень странно, лучше явно передавать устанавливаемое значение в метод

2017-03-27 13:23 UTC, gagarski commented on src/Request.kt
> +            val result = Request(word)
Обычно поля билдера передают в приватный конструктор, а сам класс делают иммутабельным (`var` -> `val`). Приватный конструктор может быть либо от кучи параметров, либо от объекта билдера.

2017-03-27 13:23 UTC, gagarski commented on src/Request.kt
> +        return when {
(Отвечая на ваш третий вопрос)
Тут, как минимум видится возможность вынести обработку `inverted` после `when`.
С остальным особо ничего не сделать, как мне кажется (нужно вызывать разные методы для регекса и для строки, а в случае с регексом - вызывать разные методы с `ignoreCase` и без).

2017-03-27 13:23 UTC, gagarski commented on src/Request.kt
> +    override fun toString(): String {
Из `Request`'а , похоже, можно сделать data-класс.

2017-03-30 09:04 UTC, gagarski commented on src/Request.kt
> +        return when {
> С остальным особо ничего не сделать, как мне кажется

Можно превратить строку в регекс (`Pattern.quote()`) и дальше работать только с регексами.

2017-03-30 09:22 UTC, gagarski commented on src/Request.kt
> +        return when {
> Можно превратить строку в регекс (Pattern.quote()) и дальше работать только с регексами.
А `toRegex` тогда можно вызвать при создании `Request`'а, на не на каждой строке.

2017-04-06 09:02 UTC, gagarski approved these changes

2017-04-06 20:18 UTC, Stupidman00 commented
1. Ввиду особенностей работы Jcommander в формат командной строки пришлось внести изменение - для передачи файлов необходимо писать ключ `-files` (`-f`). Также порядок следования ключей не фиксирован. Допустимо ли это?
2. В текущей версии создается объект `Filter` со свойствами `reader`, `writer` и `request`. В принципе, их можно превратить в аргументы метода `filter()`. Какой способ лучше?
3. При закрытии `writer`'а в методе `filter()` в дальнейшем записать данные в этот поток не получается. Данная проблема мешает добавить такую функциональность как обработка нескольких файлов за один запуск программы. Можно контролировать закрытие потока за пределами метода и не закрывать поток внутри метода (и это работает), но на мой взгляд это не надежно.
4. По поводу обработки regex'ов в классе `Request`. Я пытался превратить строку в regex, а потом при создании `Request`'а вызывать `toRegex()`, затем при проверке на нечувствительность к регистру добавлять к опциям regex'а `RegexOption.IGNORE_CASE`. Но тесты падали, точную причину не выяснил. Поэтому, так как времени мало, я остановлюсь на том, что есть.

2017-04-06 22:12 UTC, gagarski commented
> Ввиду особенностей работы Jcommander в формат командной строки пришлось внести изменение - для передачи файлов необходимо писать ключ -files (-f). Также порядок следования ключей не фиксирован. Допустимо ли это?

У вас основная проблема в том, что вы в своём парсере пытаетесь решить задачу, которую решает окружение, запускающее программу (сборка слова для поиска по частям). Например, при вызове вашей программы каким-нибудь из следующих слособов:
```java
java -jar Crep.jar -i -v "some word to search" file.txt
# или
java -jar Crep.jar -i -v some\ word\ to\ search file.txt
```
массив `argv`, переданный в `main` будет содержать следующие элементы: `-i`, `-v` `some word to search` и `file.txt`. Это работает и в `cmd` и в `bash` и в командной строке, задаваемой из Идеи. Изобретать замену данной возможности не нужно, да и полноценно не получится (попробуйте в вашем варианте вставить несколько пробелов внутри слова для поиска). Таким образом, `word` - это один аргумент в списке позиционных (которые просто `@Parameter`), а второй - имя файла (можно считать все оставшиеся именами файлов, но по заданию обработка нескольких файлов не требуется). 

По поводу порядка аргументов - произвольный порядок ключей (`-i -v`)и параметров, задаваемых ключами (`-x param_value -y param_value2`) - это не только допустимо, но и правильно. Позиционные аргументы (`word input_name.txt`), естественно, должны следовать в определённом порядке, поскольку их значение определяется их позицией.

> В текущей версии создается объект Filter со свойствами reader, writer и request. В принципе, их можно превратить в аргументы метода filter(). Какой способ лучше?

Мне кажется логичным оставить `request` в конструкторе а `reader` и  `writer`. Таким образом можно создать фильтр с запросом и переиспользовать его для разных потоков. В других случаях создание объекта выглядит странным (логически сводится к простому вызову функции).

> При закрытии writer'а в методе filter() в дальнейшем записать данные в этот поток не получается. Данная проблема мешает добавить такую функциональность как обработка нескольких файлов за один запуск программы. Можно контролировать закрытие потока за пределами метода и не закрывать поток внутри метода (и это работает), но на мой взгляд это не надежно.

Концептуально закрывать поток, открытый кем-то снаружи - не очень хорошая идея, тот, кто его создал должен его и закрыть (а вдруг в клиентском коде нужно дописать в выходной поток что-то ещё?).

2017-04-06 22:30 UTC, gagarski requested changes

2017-04-06 22:30 UTC, gagarski commented on src/Crep.kt
> +            catch (e: Exception) {
Любое ли исключение значит, что файл не найден?

2017-04-06 22:30 UTC, gagarski commented on src/Crep.kt
> +                println("This file not found: $filename")
Сообщение об ошибке лучше написать в `System.stderr`. Дело в том, что утилиты командной строки вроде `grep` часто используются в конвейере (https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D0%B9%D0%B5%D1%80_(UNIX)), то есть вывод одной команды передаётся на вход другой команды. Печать выходных данных и ошибок в один поток сильно затрудняет работу с ковейерами.

2017-04-06 22:30 UTC, gagarski commented on src/Request.kt
> +        fun build(): Request {
Вспомните про однострочную форму записи функций в Котлине (`fun f(x: Int) = x + 42`)

2017-04-06 22:30 UTC, gagarski commented on src/Request.kt
> +        fun setIgnoreCase(value: Boolean): Builder {
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/apply.html

2017-04-06 22:30 UTC, gagarski commented on src/Request.kt
> +        return inverted xor when {
Хорошо, что вы разобрались в булевских функциях и осознали, что XOR можно интерпретировать, как условную инверсию. Но лучше бы знать меру в таких хитростях. Если записать условие в натуральном виде (в виде условного оператора), код будет более понятен и легко читаем.

2017-04-12 07:46 UTC, gagarski approved these changes

2017-04-12 07:49 UTC, gagarski commented
Пока осталась проблема со склеиванием `word` из аргументов (см. предыдущий комментарий). Если её убрать, то должно быть легко привести командную строку в соответствие к заданию.

2017-04-26 19:46 UTC, gagarski commented
Вроде всё ок, можно мёржить.

2017-05-02 05:13 UTC, merged